---
name: Validate GeoFeed

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate_geofeed:
    runs-on: ubuntu-latest
    name: IETF Geofeed Validation Script
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ipdata

      - name: Validate Geofeed
        run: ipdata validate geofeed.csv
